import os
import shutil
import json
import subprocess
from pathlib import Path


def update_gitignore(project_path: Path, files_to_ignore: list):
    """.gitignore に指定されたファイルがない場合、追記する"""
    gitignore_path = project_path / ".gitignore"

    # .gitignore が存在しない場合は作成
    if not gitignore_path.exists():
        with open(gitignore_path, "w") as f:
            f.write("# Generated by gemini-core broadcaster\n")

    with open(gitignore_path, "r") as f:
        content = f.read()

    new_entries = []
    for file_name in files_to_ignore:
        if file_name not in content:
            new_entries.append(file_name)

    if new_entries:
        print(f"   📝 Updating .gitignore in {project_path.name}")
        with open(gitignore_path, "a") as f:
            if not content.endswith("\n"):
                f.write("\n")
            f.write("\n# 写像系規約ファイル（gemini-docsが正典）\n")
            for entry in new_entries:
                f.write(f"{entry}\n")


import time


def unstage_files(project_path: Path, files_to_unstage: list):
    """git rm --cached を実行して Git の監視から外す"""
    if not (project_path / ".git").exists():
        return

    for file_name in files_to_unstage:
        try:
            # ファイルが Git の追跡対象か確認
            result = subprocess.run(
                ["git", "ls-files", "--error-unmatch", file_name],
                cwd=str(project_path),
                capture_output=True,
                text=True,
                check=False,
            )
            if result.returncode == 0:
                print(f"   🧹 Untracking managed file: {file_name}")
                subprocess.run(
                    ["git", "rm", "--cached", file_name],
                    cwd=str(project_path),
                    capture_output=True,
                    check=False,
                )
        except Exception as e:
            print(
                f"   ⚠️  Warning: Failed to unstage {file_name} in {project_path.name}: {e}"
            )


def broadcast():
    core_root = Path("/home/irom/dev/gemini-core")
    docs_root = Path("/home/irom/dev/gemini-docs")
    dev_root = core_root.parent

    # 配信対象プロジェクトの取得 (gemini-core/projects.json を正典とする)
    projects_file = core_root / "projects.json"
    if not projects_file.exists():
        print(f"Error: {projects_file} not found.")
        return

    with open(projects_file, "r") as f:
        projects = json.load(f)

    # 配信対象ファイル (gemini-docs から配信)
    managed_files = ["GEMINI.md", ".antigravityrules", "anti_patterns.md"]

    print(f"🚀 Broadcaster: Syncing Master Rules from {docs_root}")

    for project_name in projects:
        project_path = dev_root / project_name
        if not project_path.exists():
            print(f"⚠️  Skipping missing project: {project_name}")
            continue

        print(f"📦 Syncing to: {project_name}")

        # 1. 先行して .gitignore を更新し、追跡を解除する
        update_gitignore(project_path, managed_files)
        unstage_files(project_path, managed_files)

        # 2. 各ファイルの物理コピー
        for file_name in managed_files:
            master_source = docs_root / file_name
            if not master_source.exists():
                print(f"   ⚠️  Master script not found in docs: {file_name}")
                continue

            target_path = project_path / file_name
            if target_path.is_symlink():
                target_path.unlink()

            if target_path.exists() and master_source.samefile(target_path):
                print(f"   ℹ️  {file_name} is already up to date (same file)")
                continue

            shutil.copy2(master_source, target_path)
            print(f"   ✅ {file_name} updated")

        # 3. エージェントスキルとワークフローの同期 (.agents/)
        agent_dir_name = ".agents"
        for sub_dir in ["skills", "workflows"]:
            source_dir = docs_root / agent_dir_name / sub_dir
            target_dir = project_path / agent_dir_name / sub_dir

            if source_dir.exists():
                print(f"   🤖 Syncing agent {sub_dir}...")
                shutil.copytree(source_dir, target_dir, dirs_exist_ok=True)
                print(f"   ✅ .agents/{sub_dir} synced")

        # 4. SPECIFICATION.md のひな形設置
        time.sleep(0.5)

    print(
        "\n✅ Broadcast complete. All projects are now in sync with gemini-docs Master rules."
    )


if __name__ == "__main__":
    broadcast()
