import os
import shutil
import json
import subprocess
import argparse
import time
from pathlib import Path
from typing import List, Union, Dict


class FileSystem:
    """物理ファイルシステムへのアクセスをカプセル化するクラス。
    テスト時に Mock へ差し替えることが可能。
    """

    def exists(self, path: Path) -> bool:
        return path.exists()

    def is_symlink(self, path: Path) -> bool:
        return path.is_symlink()

    def unlink(self, path: Path):
        path.unlink()

    def samefile(self, path1: Path, path2: Path) -> bool:
        try:
            return path1.samefile(path2)
        except OSError:
            return False

    def copy2(self, src: Path, dest: Path):
        shutil.copy2(src, dest)

    def copytree(self, src: Path, dest: Path, ignore=None):
        shutil.copytree(src, dest, dirs_exist_ok=True, ignore=ignore)

    def read_text(self, path: Path) -> str:
        return path.read_text()

    def write_text(self, path: Path, content: str):
        path.write_text(content)

    def append_text(self, path: Path, content: str):
        with open(path, "a") as f:
            f.write(content)

    def run_command(self, args: List[str], cwd: Path) -> subprocess.CompletedProcess:
        return subprocess.run(
            args, cwd=str(cwd), capture_output=True, text=True, check=False
        )


class Broadcaster:
    def __init__(self, fs: FileSystem, dry_run: bool = False):
        self.fs = fs
        self.dry_run = dry_run
        # 管理対象ファイル群（規約の物理写像）
        self.managed_files = ["GEMINI.md", ".antigravityrules", "anti_patterns.md"]
        # 管理対象ディレクトリ（規約・政策エンジン）
        self.managed_dirs = ["policy"]

    def _log_action(self, msg: str):
        prefix = "[DRY-RUN] " if self.dry_run else ""
        print(f"{prefix}{msg}")

    def update_gitignore(self, project_path: Path):
        """.gitignore に指定されたファイルがない場合、追記する"""
        gitignore_path = project_path / ".gitignore"

        if not self.fs.exists(gitignore_path):
            if not self.dry_run:
                self.fs.write_text(gitignore_path, "# Generated by gemini-core broadcaster\n")
            self._log_action(f"   📝 Created .gitignore in {project_path.name}")

        content = self.fs.read_text(gitignore_path) if self.fs.exists(gitignore_path) else ""

        all_managed = self.managed_files + self.managed_dirs
        new_entries = [f for f in all_managed if f not in content]

        if new_entries:
            self._log_action(f"   📝 Updating .gitignore in {project_path.name} (Adding: {', '.join(new_entries)})")
            if not self.dry_run:
                suffix = "\n" if content and not content.endswith("\n") else ""
                addition = suffix + "\n# 写像系規約ファイル（gemini-docsが正典）\n"
                for entry in new_entries:
                    addition += f"{entry}\n"
                self.fs.append_text(gitignore_path, addition)

    def unstage_files(self, project_path: Path):
        """git rm --cached を実行して Git の監視から外す"""
        if not self.fs.exists(project_path / ".git"):
            return

        for entry in self.managed_files + self.managed_dirs:
            try:
                # ファイル/ディレクトリが Git の追跡対象か確認
                result = self.fs.run_command(["git", "ls-files", "--error-unmatch", entry], project_path)
                if result.returncode == 0:
                    self._log_action(f"   🧹 Untracking managed entry: {entry}")
                    if not self.dry_run:
                        self.fs.run_command(["git", "rm", "-rf", "--cached", entry], project_path)
            except Exception as e:
                print(f"   ⚠️  Warning: Failed to unstage {entry} in {project_path.name}: {e}")

    def sync_project(self, p_id: str, project_path: Path, docs_root: Path):
        """単一プロジェクトの同期を実行"""
        self._log_action(f"📦 Syncing to: {p_id}")

        # 1. .gitignore 更新と unstage
        self.update_gitignore(project_path)
        self.unstage_files(project_path)

        # 2. 各ファイルの物理コピー
        for file_name in self.managed_files:
            master_source = docs_root / file_name
            if not self.fs.exists(master_source):
                print(f"   ⚠️  Master script not found in docs: {file_name}")
                continue

            target_path = project_path / file_name
            if self.fs.is_symlink(target_path):
                self._log_action(f"   🔗 Removing symlink: {file_name}")
                if not self.dry_run:
                    self.fs.unlink(target_path)

            if self.fs.exists(target_path) and self.fs.samefile(master_source, target_path):
                print(f"   ℹ️  {file_name} is already up to date (same file)")
                continue

            self._log_action(f"   ✅ Updating {file_name}")
            if not self.dry_run:
                self.fs.copy2(master_source, target_path)

        # 3. 規約ディレクトリ (policy/) の同期
        for dir_name in self.managed_dirs:
            source_dir = docs_root / dir_name
            target_dir = project_path / dir_name
            
            if self.fs.exists(source_dir):
                # 自身へのコピーを防止
                try:
                    if source_dir.resolve() == target_dir.resolve():
                        continue
                except: pass

                self._log_action(f"   📂 Syncing dir: {dir_name} (excluding project-context.yaml)")
                if not self.dry_run:
                    # project-context.yaml (原点アンカー) を除外して同期
                    self.fs.copytree(source_dir, target_dir, 
                                    ignore=shutil.ignore_patterns("project-context.yaml"))

        # 4. エージェントスキルとワークフローの同期 (.agents/)
        agent_dir_name = ".agents"
        for sub_dir in ["skills", "workflows"]:
            source_dir = docs_root / agent_dir_name / sub_dir
            target_dir = project_path / agent_dir_name / sub_dir

            if self.fs.exists(source_dir):
                # 自身へのコピーを防止
                try:
                   if source_dir.resolve() == target_dir.resolve():
                        print(f"   ℹ️  {agent_dir_name}/{sub_dir} is source (skipping self-copy)")
                        continue
                except (OSError, FileNotFoundError):
                    pass

                self._log_action(f"   🤖 Syncing agent {sub_dir}...")
                if not self.dry_run:
                    self.fs.copytree(source_dir, target_dir)

        if not self.dry_run:
            time.sleep(0.5)

    def run(self, projects: list, dev_root: Path, docs_root: Path):
        """全プロジェクトの同期を開始"""
        print(f"🚀 Broadcaster: Syncing Master Rules from {docs_root}")
        if self.dry_run:
            print("🛡️  Dry-run mode enabled. No physical changes will be made.")

        for project in projects:
            if isinstance(project, dict):
                p_id = project["id"]
                p_rel_path = project.get("path") or p_id
            else:
                p_id = project
                p_rel_path = project

            project_path = dev_root / p_rel_path
            if not self.fs.exists(project_path):
                print(f"⚠️  Skipping missing project: {p_id} (Attempted path: {project_path})")
                continue

            self.sync_project(p_id, project_path, docs_root)

        print("\n✅ Broadcast operation complete.")


def broadcast():
    parser = argparse.ArgumentParser(description="gemini-core broadcarster")
    parser.add_argument("--dry-run", action="store_true", help="Do not perform actual sync")
    args = parser.parse_args()

    core_root = Path("/home/irom/dev/gemini-core")
    docs_root = Path("/home/irom/dev/gemini-docs")
    dev_root = core_root.parent

    projects_file = core_root / "projects.json"
    if not projects_file.exists():
        print(f"Error: {projects_file} not found.")
        return

    with open(projects_file, "r") as f:
        projects = json.load(f)

    fs = FileSystem()
    broadcaster = Broadcaster(fs, dry_run=args.dry_run)
    broadcaster.run(projects, dev_root, docs_root)


if __name__ == "__main__":
    broadcast()
